-- liquibase formatted sql

-- changeset astrelchenko:1
create table colors (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT
);
create table socks_stock(
                              id bigint generated by default as identity primary key,
                              cotton_part INTEGER not null,
                              quantity INTEGER not null,
                              color_id bigint references colors(id)
);

-- changeset astrelchenko:2
alter table socks_stock
    add constraint cotton_part_constraint check ( cotton_part >= 0 and cotton_part <= 100 );