-- liquibase formatted sql

-- changeset astrelchenko:1
create table colors
(

    id   bigint generated by default as identity primary key,
    name varchar unique not null
);
create table socks_stock
(
    id          bigint generated by default as identity primary key,
    cotton_part int not null,
    quantity    int not null,
    color_id    bigint references colors (id) on delete cascade
);

-- changeset astrelchenko:2
alter table socks_stock
    add constraint cotton_part_constraint check ( cotton_part >= 0 and cotton_part <= 100 );